definitions:
  rkentry.ProcessInfo:
    properties:
      appName:
        type: string
      az:
        type: string
      cpuInfo:
        $ref: '#/definitions/rkos.CpuInfo'
      description:
        type: string
      docsUrl:
        items:
          type: string
        type: array
      domain:
        type: string
      gid:
        type: string
      goEnvInfo:
        $ref: '#/definitions/rkos.GoEnvInfo'
      homeUrl:
        type: string
      keywords:
        items:
          type: string
        type: array
      maintainers:
        items:
          type: string
        type: array
      memInfo:
        $ref: '#/definitions/rkos.MemInfo'
      netInfo:
        $ref: '#/definitions/rkos.NetInfo'
      osInfo:
        $ref: '#/definitions/rkos.OsInfo'
      realm:
        type: string
      region:
        type: string
      startTime:
        type: string
      uid:
        type: string
      upTimeSec:
        type: integer
      username:
        type: string
      version:
        type: string
    type: object
  rkentry.aliveResp:
    properties:
      alive:
        type: boolean
    type: object
  rkentry.gcResp:
    properties:
      memStatAfterGc:
        $ref: '#/definitions/rkos.MemInfo'
      memStatBeforeGc:
        $ref: '#/definitions/rkos.MemInfo'
    type: object
  rkentry.readyResp:
    properties:
      ready:
        type: boolean
    type: object
  rkos.CpuInfo:
    properties:
      count:
        type: integer
    type: object
  rkos.GoEnvInfo:
    properties:
      goArch:
        type: string
      goos:
        type: string
      routinesCount:
        type: integer
      version:
        type: string
    type: object
  rkos.MemInfo:
    properties:
      forceGcCount:
        type: integer
      gcCountTotal:
        type: integer
      lastGcTimestamp:
        type: string
      memAllocByte:
        type: integer
      memUsedMb:
        type: integer
      memUsedPercentage:
        type: number
      sysAllocByte:
        type: integer
    type: object
  rkos.NetInfo:
    properties:
      netInterface:
        items:
          $ref: '#/definitions/rkos.netInterface'
        type: array
    type: object
  rkos.OsInfo:
    properties:
      arch:
        type: string
      hostname:
        type: string
      os:
        type: string
    type: object
  rkos.netInterface:
    properties:
      addrs:
        description: A list of unicast interface addresses for a specific interface.
        items:
          type: string
        type: array
      flags:
        description: e.g., FlagUp, FlagLoopback, FlagMulticast
        items:
          type: string
        type: array
      hardwareAddr:
        description: IEEE MAC-48, EUI-48 and EUI-64 form
        type: string
      mtu:
        description: maximum transmission unit
        type: integer
      multicastAddrs:
        description: A list of multicast, joined group addresses for a specific interface
        items:
          type: string
        type: array
      name:
        description: e.g., "en0", "lo0", "eth0.100"
        type: string
    type: object
info:
  contact:
    email: lark@pointgoal.io
    name: rk-dev
    url: https://github.com/rookie-ninja/rk-entry
  description: This is builtin RK common service.
  license:
    name: Apache 2.0 License
    url: https://github.com/rookie-ninja/rk-entry/blob/master/LICENSE.txt
  title: RK Common Service
  version: "2.0"
paths:
  /rk/v1/alive:
    get:
      operationId: "2"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rkentry.aliveResp'
      security:
      - ApiKeyAuth: []
      - BasicAuth: []
      - JWT: []
      summary: Get application liveness status
  /rk/v1/gc:
    get:
      operationId: "3"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rkentry.gcResp'
      security:
      - ApiKeyAuth: []
      - BasicAuth: []
      - JWT: []
      summary: Trigger Gc
  /rk/v1/info:
    get:
      operationId: "4"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rkentry.ProcessInfo'
      security:
      - ApiKeyAuth: []
      - BasicAuth: []
      - JWT: []
      summary: Get application and process info
  /rk/v1/ready:
    get:
      operationId: "1"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rkentry.readyResp'
      security:
      - ApiKeyAuth: []
      - BasicAuth: []
      - JWT: []
      summary: Get application readiness status
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-Key
    type: apiKey
  BasicAuth:
    type: basic
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
